# Generated by Django 5.0.6 on 2024-06-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_point_index_alter_point_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='id',
            new_name='index',
        ),
    ]
