# Generated by Django 5.0.6 on 2024-06-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_index_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='categoria',
            field=models.TextField(),
        ),
    ]
